### PR TITLE
Removed breaking typing_extensions import

### LINKED ISSUE #180: typing_extensions breaks Python 3.12
typing_extensions requires python < 3.11

I propose either removing and utilizing the "Q" instead of Self where it's currently being used.

Alternatively putting it behind and `if TYPE_CHECKING:` condition so it doesn't hit at runtime.

### PR DESCRIPTION
**Pull request by BillSchumacher**
Resolves #180

### CODE REVIEW

**Comment by BillSchumacher** [comment]
Seems like mypy might require this package so I don't think it can be removed.

**Comment by wesleykendall** [comment]
When you say "breaking", do you mean the code causes an error in Python 3.12? Do you not have `typing-extensions` installed in your environment?

I verified that I can `pip install typing-extensions` on Python 3.12, so it doesn't seem like there's a limitation of installing it with python 3.12 as mentioned in #180. It does seem like we don't automatically include this as a dependency.

I will defer this one to @max-muoto , but the better approach is probably conditionally installing `typing-extensions` in our package metadata and conditionally importing the types based on the Python version. Or perhaps its common for packages to just include this as a dependency. I think `Self` is likely the more accurate type here though

**Comment by BillSchumacher** [comment]
Yes, exactly so when installing this as a dependency typing-extensions is not installed on 3.11 or 3.12 as it requires < 3.11 https://github.com/BillSchumacher/django-audimatic/actions/runs/11563973687/job/32188306870

**Comment by BillSchumacher** [comment]
Either way I'm not sure that the import is actually needed.

**Comment by max-muoto** [comment]
Thanks @BillSchumacher. Can merge this and bump the version.

**Pull request merged**
